codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 75%
        threshold: 2%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
  - "**/__tests__/**"
  - "**/jest.config.js"
  - "**/jest.setup.js"
  - "**/next.config.js"
  - "**/tailwind.config.ts"
  - "**/postcss.config.mjs"
  - "**/*.d.ts"
