/**
 * Icons Component
 * 
 * Centralized icon components using lucide-react
 */

import {
  Loader2,
  Check,
  X,
  AlertTriangle,
  Clock,
  ExternalLink,
  Twitter,
  UserPlus,
  Heart,
  Repeat,
  Info,
  Zap,
  Coins,
  RefreshCw as Refresh,
  Unlink,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Search,
  Filter,
  Download,
  Upload,
  Settings,
  User,
  Users,
  Mail,
  Bell,
  Home,
  BarChart,
  FileText,
  Calendar,
  Copy,
  Eye,
  EyeOff,
  Edit,
  Trash,
  Plus,
  Minus,
  MoreVertical,
  MoreHorizontal,
  LogOut,
  LogIn,
  Shield,
  Lock,
  Unlock,
  Key,
  Wallet,
  TrendingUp,
  TrendingDown,
  Activity,
  Award,
  Target,
  Gift,
  Star,
  Flag,
  Tag,
  Link,
  Share2,
  MessageSquare,
  Send,
  Archive,
  Bookmark,
  CheckCircle,
  XCircle,
  AlertCircle,
  HelpCircle,
  InfoIcon,
  Menu,
  Grid,
  List,
  Layout,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  RotateCw,
  RotateCcw,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsDown,
  type LucideIcon,
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  check: Check,
  x: X,
  alertTriangle: AlertTriangle,
  clock: Clock,
  externalLink: ExternalLink,
  twitter: Twitter,
  userPlus: UserPlus,
  heart: Heart,
  repeat: Repeat,
  info: Info,
  zap: Zap,
  coins: Coins,
  refresh: Refresh,
  unlink: Unlink,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  search: Search,
  filter: Filter,
  download: Download,
  upload: Upload,
  settings: Settings,
  user: User,
  users: Users,
  mail: Mail,
  bell: Bell,
  home: Home,
  barChart: BarChart,
  fileText: FileText,
  calendar: Calendar,
  copy: Copy,
  eye: Eye,
  eyeOff: EyeOff,
  edit: Edit,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  logOut: LogOut,
  logIn: LogIn,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  wallet: Wallet,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  activity: Activity,
  award: Award,
  target: Target,
  gift: Gift,
  star: Star,
  flag: Flag,
  tag: Tag,
  link: Link,
  share: Share2,
  message: MessageSquare,
  send: Send,
  archive: Archive,
  bookmark: Bookmark,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  helpCircle: HelpCircle,
  infoCircle: InfoIcon,
  menu: Menu,
  grid: Grid,
  list: List,
  layout: Layout,
  maximize: Maximize,
  minimize: Minimize,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  rotateCw: RotateCw,
  rotateCcw: RotateCcw,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronsUp: ChevronsUp,
  chevronsDown: ChevronsDown,
} as const;

export type IconName = keyof typeof Icons;
export type { LucideIcon };
